apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "lmos-operator.fullname" . }}
  labels:
    {{- include "lmos-operator.labels" . | nindent 4 }}
rules:
  # Permissions to create Custom Resource Definitions (CRDs)
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]

  # Permissions to create custom resources
  - apiGroups: ["{{ .Values.customApiGroup }}"]
    resources:
      {{- range .Values.customResources }}
      - "{{ . }}"
      {{- end }}
    verbs: ["get", "list", "create", "update", "delete", "watch", "patch"]