apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "lmos-operator.fullname" . }}
  labels:
    {{- include "lmos-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lmos-operator.fullname" . }}
    namespace: {{ .Values.serviceAccount.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "lmos-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io