# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches:
      - '**'

jobs:
  CI:
    uses: eclipse-lmos/.github/.github/workflows/ci.yml@pipeline
#    with:
#      git-ref: github.ref
    secrets:
      oss-username: ${{ secrets.OSSRH_USERNAME }}
      oss-password: ${{ secrets.OSSRH_PASSWORD }}
      signing-key-id: ${{ secrets.GPG_SUBKEY_ID }}
      signing-key: ${{ secrets.GPG_PRIVATE_KEY }}
      signing-key-password: ${{ secrets.GPG_PASSPHRASE }}
      registry-username: ${{ github.actor }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
